version: '3'
services:
  bitespeed-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bitespeed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - bitespeed-net

  bitespeed:
    build: .
    environment:
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: bitespeed-postgres
      PG_PORT: 5432
      PG_DATABASE: bitespeed
      ISMIGRATION: false
      PORT: 80
      ENV: 'production'
    ports:
      - "80:80"
    networks:
      - bitespeed-net
    depends_on:
      - bitespeed-postgres
volumes:
  postgres_data2:

networks:
  bitespeed-net: